/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Deal = IDL.Record({
  'badgeLabel' : IDL.Text,
  'title' : IDL.Text,
  'tagLabel' : IDL.Text,
});
export const Offer = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'commissionPercentage' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
  'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
  'getTotalAffiliatesJoined' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalOffersAvailable' : IDL.Func([], [IDL.Nat], ['query']),
  'getTotalPayoutsMade' : IDL.Func([], [IDL.Nat], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Deal = IDL.Record({
    'badgeLabel' : IDL.Text,
    'title' : IDL.Text,
    'tagLabel' : IDL.Text,
  });
  const Offer = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'commissionPercentage' : IDL.Nat,
  });
  
  return IDL.Service({
    'getAllDeals' : IDL.Func([], [IDL.Vec(Deal)], ['query']),
    'getAllOffers' : IDL.Func([], [IDL.Vec(Offer)], ['query']),
    'getTotalAffiliatesJoined' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalOffersAvailable' : IDL.Func([], [IDL.Nat], ['query']),
    'getTotalPayoutsMade' : IDL.Func([], [IDL.Nat], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };